<!DOCTYPE html>
<html lang="en">

<head>
    <?php $this->getChildHtml("head"); ?>
</head>

<body>
    <div class="header">
        <?php $this->getChildHtml("header"); ?>
    </div>
    <!-- <pre><?php //print_r($_REQUEST); ?></pre> -->

    <div class="content">
        <?php $this->getChildHtml("content"); ?>
    </div>
    <div class="footer">
        <?php $this->getChildHtml("footer"); ?>
    </div>
</body>

</html>